# Generated by Django 5.2 on 2025-04-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_create_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otdel',
            name='flor',
            field=models.IntegerField(),
        ),
    ]
